// report.js — 리뷰 결과를 마크다운 리포트로 생성
import fs from 'fs';
import path from 'path';

/**
 * 분류 결과를 마크다운 리포트로 생성하고 Inbox에 저장
 */
export function generateAndSaveReport(results, vaultDir) {
  const date = new Date().toISOString().split('T')[0];
  const content = generateReport(results, date);

  const reportPath = path.join(vaultDir, 'Inbox', `Nightly-Synapse_${date}.md`);
  fs.writeFileSync(reportPath, content, 'utf-8');

  return reportPath;
}

function generateReport(results, date) {
  const promotes = results.filter(r => r.classification?.action === 'slip_box_promote');
  const keeps = results.filter(r => r.classification?.action === 'keep');
  const moves = results.filter(r => r.classification?.action === 'move');
  const errors = results.filter(r => r.classification?.error);

  return `---
tags: [system/nightly-synapse]
created: ${date}
---

# Nightly Synapse Review — ${date}

> 오늘 수정된 노트 ${results.length}개를 Ground Truth 기준으로 점검했습니다.
> **이 리포트는 제안일 뿐입니다. 실행 전에 반드시 검토하세요.**

---

## Slip-Box 승격 후보 (${promotes.length}개)

${promotes.length === 0 ? '_없음_\n' : promotes.map(r => {
  const s = r.classification.slip_box;
  return `### ${r.note}
- **제안 파일명**: \`${s.suggested_name}\`
- **위치**: \`0. Slip-Box/${s.subfolder}/\`
- **루만 넘버링**: ${s.luhmann}
- **PKM 태그**: #${s.pkm_tag}
- **연결 노트**: ${s.connections.map(c => `[[${c}]]`).join(', ')}
- **브릿지 키워드**: ${s.bridge_keywords.join(' ')}
- **이유**: ${r.classification.reason}
- **핵심 요약**: ${r.classification.summary}

> **제안 본문**:
> ${s.rewritten_content}
`;
}).join('\n')}

---

## 현재 위치 유지 (${keeps.length}개)

${keeps.length === 0 ? '_없음_\n' : keeps.map(r => `- **${r.note}** — ${r.classification.summary}`).join('\n')}

---

## 이동 제안 (${moves.length}개)

${moves.length === 0 ? '_없음_\n' : moves.map(r => `- **${r.note}** → \`${r.classification.suggested_move_to}\` — ${r.classification.reason}`).join('\n')}

${errors.length > 0 ? `
---

## 처리 오류 (${errors.length}개)

${errors.map(r => `- **${r.note}**: ${r.classification.error}`).join('\n')}
` : ''}
---

_Generated by Nightly Synapse at ${new Date().toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' })}_
`;
}
